/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emplyee.payroll;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
/**
 *
 * @author Life
 */
public class login extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form login
     */
    
    public login() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        
        currentDate();
        lbl_U.setVisible(false);
        lbl_P.setVisible(false);
        lbl_C.setVisible(false);
    }
    public void  currentDate(){
    
         Calendar  cal = new GregorianCalendar();
         int month = cal.get(Calendar.MONTH);
         int year = cal.get(Calendar.YEAR);
         int day = cal.get(Calendar.DAY_OF_MONTH);
         
         
         lbl_Date.setText((month+1)+"/"+day+"/"+year);
         
         int second = cal.get(Calendar.SECOND);
         int minute = cal.get(Calendar.MINUTE);
         int hour = cal.get(Calendar.HOUR);
         
         lbl_Time.setText(hour+":"+(minute)+":"+second);
         
        
        
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_combo = new javax.swing.JComboBox();
        txt_username = new javax.swing.JTextField();
        lbl_U = new javax.swing.JLabel();
        lbl_P = new javax.swing.JLabel();
        lbl_C = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBoxShowPass = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        lbl_Date = new javax.swing.JMenu();
        lbl_Time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please Enter your username and password here!:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 310, 350, 17);

        jLabel2.setText("Username:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 370, 70, 14);

        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 410, 70, 14);

        jLabel4.setText("Select Division:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 450, 100, 14);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 480, 100, 30);

        txt_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Sales" }));
        jPanel1.add(txt_combo);
        txt_combo.setBounds(160, 440, 210, 30);
        jPanel1.add(txt_username);
        txt_username.setBounds(160, 360, 210, 30);

        lbl_U.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_U.setForeground(new java.awt.Color(255, 0, 0));
        lbl_U.setText("*");
        jPanel1.add(lbl_U);
        lbl_U.setBounds(380, 370, 9, 17);

        lbl_P.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_P.setForeground(new java.awt.Color(255, 0, 0));
        lbl_P.setText("*");
        jPanel1.add(lbl_P);
        lbl_P.setBounds(380, 410, 9, 17);

        lbl_C.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_C.setForeground(new java.awt.Color(255, 0, 0));
        lbl_C.setText("*");
        jPanel1.add(lbl_C);
        lbl_C.setBounds(380, 450, 9, 17);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(160, 400, 210, 30);

        jCheckBoxShowPass.setBackground(new java.awt.Color(204, 204, 204));
        jCheckBoxShowPass.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxShowPass.setText("Show Password");
        jCheckBoxShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPassActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxShowPass);
        jCheckBoxShowPass.setBounds(410, 410, 120, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Life\\Documents\\NetBeansProjects\\Emplyee Payroll\\src\\emplyee\\payroll\\images\\kent3.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 980, 530);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        lbl_Date.setText("Date");
        jMenuBar1.add(lbl_Date);

        lbl_Time.setText("Time");
        jMenuBar1.add(lbl_Time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        lbl_U.setVisible(false);
       lbl_P.setVisible(false);
       lbl_C.setVisible(false);
        if(txt_username.getText().equals(""))
       {
       lbl_U.setVisible(true);
       }if(String.valueOf(jPasswordField1.getPassword()).equals(""))
       {
         lbl_P.setVisible(true);
       }if(String.valueOf(txt_combo.getSelectedItem()).equals(""))
        {
       lbl_C.setVisible(true);
        }
       else { 
        Connection conn = db.getConnection();
           PreparedStatement pst;
        
        try{
        
            
            int count = 0;
            
           pst = conn.prepareStatement("SELECT * FROM user WHERE username = ? AND password = ? AND division = ?");
            
             pst.setString(1,txt_username.getText());
             pst.setString(2,String.valueOf(jPasswordField1.getPassword()));
             pst.setString(3,String.valueOf(txt_combo.getSelectedItem().toString()));
            
            rs = pst.executeQuery();
            while(rs.next()){
             int id = rs.getInt(1);
             Emp.empid = id;
             count  = count+1;
            }
            String access = (txt_combo.getSelectedItem().toString());
            
            if("Admin".equals(access)){
                if(count ==1) {
                
               JOptionPane.showMessageDialog(null,"Success");
               MainMenu j = new MainMenu();
               j.setVisible(true);
               this.dispose();
               
                }else{
                
                JOptionPane.showMessageDialog(null,"Username and Password you entered are wrong!");
                }
           
            }
        
        }
        
       catch (SQLException ex) {
               Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally {
            try{
               rs.close();
            
            }catch (Exception e){
            
            }
        
        }
        
        
        
       } 
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPassActionPerformed
        if(jCheckBoxShowPass.isSelected()){
            jPasswordField1.setEchoChar((char)0);
        }else {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxShowPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lbl_C;
    private javax.swing.JMenu lbl_Date;
    private javax.swing.JLabel lbl_P;
    private javax.swing.JMenu lbl_Time;
    private javax.swing.JLabel lbl_U;
    private javax.swing.JComboBox txt_combo;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
