/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package healthserviceautomatedsystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author madman
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public mainForm() 
    {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    public void hide1()
{
       lbladmn.setVisible(false);
       mnu1.setVisible(false);
}
    public void hide2()
    {
      lbldoc.setVisible(false);
      mnu2.setVisible(false);
    }
         public void hide3()
    {
      lblreceptionist.setVisible(false); 
      mnu3.setVisible(false);
    }   
       public void hide4()
       {
        lbllab.setVisible(false); 
        mnu4.setVisible(false);
       }
       public void hide5()
       {
       lblpay.setVisible(false);
       mnu5.setVisible(false);
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbladmn = new javax.swing.JLabel();
        lblpay = new javax.swing.JLabel();
        lblreceptionist = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbldoc = new javax.swing.JLabel();
        lbllab = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnu1 = new javax.swing.JMenuItem();
        mnu2 = new javax.swing.JMenuItem();
        mnu3 = new javax.swing.JMenuItem();
        mnu4 = new javax.swing.JMenuItem();
        mnu5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Health Service Automated System");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TMC_Clinic_Waiting_Area.JPG"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), null));

        lbladmn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ControlPanel.png"))); // NOI18N
        lbladmn.setText("Administrator panel");
        lbladmn.setToolTipText("Administrator control panel");
        lbladmn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladmnMouseClicked(evt);
            }
        });

        lblpay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallet.png"))); // NOI18N
        lblpay.setText("Payment");
        lblpay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpayMouseClicked(evt);
            }
        });
        lblpay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblpayKeyPressed(evt);
            }
        });

        lblreceptionist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recptn.png"))); // NOI18N
        lblreceptionist.setText("Reception");
        lblreceptionist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblreceptionistMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SignOut.png"))); // NOI18N
        jLabel2.setText("Log out");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        lbldoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doc.jpg"))); // NOI18N
        lbldoc.setText("Doctor");
        lbldoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldocMouseClicked(evt);
            }
        });

        lbllab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lab.png"))); // NOI18N
        lbllab.setText("Laboratory");
        lbllab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbladmn)
                .addGap(18, 18, 18)
                .addComponent(lbldoc)
                .addGap(18, 18, 18)
                .addComponent(lblreceptionist)
                .addGap(18, 18, 18)
                .addComponent(lbllab)
                .addGap(18, 18, 18)
                .addComponent(lblpay)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbladmn)
                .addComponent(lblpay)
                .addComponent(lblreceptionist)
                .addComponent(jLabel2)
                .addComponent(lbldoc)
                .addComponent(lbllab))
        );

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("justus simiyu @2017");
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        mnu1.setText("Administrator Panel");
        mnu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu1ActionPerformed(evt);
            }
        });
        jMenu1.add(mnu1);

        mnu2.setText("Doctor");
        mnu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu2ActionPerformed(evt);
            }
        });
        jMenu1.add(mnu2);

        mnu3.setText("Receptionist");
        mnu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu3ActionPerformed(evt);
            }
        });
        jMenu1.add(mnu3);

        mnu4.setText("Laboratory");
        mnu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu4ActionPerformed(evt);
            }
        });
        jMenu1.add(mnu4);

        mnu5.setText("Cashier");
        mnu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu5ActionPerformed(evt);
            }
        });
        jMenu1.add(mnu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("System");

        jMenuItem8.setText("Log out");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem1.setText("Help Contents");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1349, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 556, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbladmnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladmnMouseClicked
    loadControlPanel();
    }//GEN-LAST:event_lbladmnMouseClicked

    private void lblreceptionistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblreceptionistMouseClicked
        reception reception = new reception();
        reception.setVisible(true);
    }//GEN-LAST:event_lblreceptionistMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        help help = new help();
        help.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        about about = new about();
        about.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void lbldocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldocMouseClicked
        doctor doctor = new doctor();
        doctor.setVisible(true);
    }//GEN-LAST:event_lbldocMouseClicked

    private void mnu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu1ActionPerformed
        loadControlPanel();
    }//GEN-LAST:event_mnu1ActionPerformed

    private void mnu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu2ActionPerformed
        doctor doctor = new doctor();
        doctor.setVisible(true);
    }//GEN-LAST:event_mnu2ActionPerformed

    private void mnu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu3ActionPerformed
        reception reception = new reception();
        reception.setVisible(true);
    }//GEN-LAST:event_mnu3ActionPerformed

    private void mnu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu4ActionPerformed
        laboratory laboratory = new laboratory();
        laboratory.setVisible(true);
    }//GEN-LAST:event_mnu4ActionPerformed

    private void lbllabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllabMouseClicked
        laboratory laboratory = new laboratory();
        laboratory.setVisible(true);
    }//GEN-LAST:event_lbllabMouseClicked

    private void mnu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu5ActionPerformed
        payments payments = new payments();
        payments.setVisible(true);
    }//GEN-LAST:event_mnu5ActionPerformed

    private void lblpayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblpayKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblpayKeyPressed

    private void lblpayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpayMouseClicked
        payments payments = new payments();
        payments.setVisible(true);
    }//GEN-LAST:event_lblpayMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int response=JOptionPane.showConfirmDialog(this, "Log Off","Confirm Action",JOptionPane.YES_NO_OPTION );
        if(response==JOptionPane.YES_OPTION)
        {
            database.closeConnection();
            dispose();
            Login login = new Login();
            login.setVisible(true);
        } 
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        int response=JOptionPane.showConfirmDialog(this, "Log Off","Confirm Action",JOptionPane.YES_NO_OPTION );
        if(response==JOptionPane.YES_OPTION)
        {
            database.closeConnection();
            dispose();
            Login login = new Login();
            login.setVisible(true);
        } 
    }//GEN-LAST:event_jMenuItem8ActionPerformed
public void loadControlPanel()
{
        controlPanel controlPanel = new controlPanel();
        controlPanel.setVisible(true);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbladmn;
    private javax.swing.JLabel lbldoc;
    private javax.swing.JLabel lbllab;
    private javax.swing.JLabel lblpay;
    private javax.swing.JLabel lblreceptionist;
    private javax.swing.JMenuItem mnu1;
    private javax.swing.JMenuItem mnu2;
    private javax.swing.JMenuItem mnu3;
    private javax.swing.JMenuItem mnu4;
    private javax.swing.JMenuItem mnu5;
    // End of variables declaration//GEN-END:variables
}
